// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: common/model/v2/friend.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 好友列表项
type FriendItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`             // 用户id
	NickName string `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName,omitempty"` // 昵称
	FaceURL  string `protobuf:"bytes,3,opt,name=faceURL,proto3" json:"faceURL,omitempty"`   // 头像
}

func (x *FriendItem) Reset() {
	*x = FriendItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_model_v2_friend_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendItem) ProtoMessage() {}

func (x *FriendItem) ProtoReflect() protoreflect.Message {
	mi := &file_common_model_v2_friend_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendItem.ProtoReflect.Descriptor instead.
func (*FriendItem) Descriptor() ([]byte, []int) {
	return file_common_model_v2_friend_proto_rawDescGZIP(), []int{0}
}

func (x *FriendItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FriendItem) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *FriendItem) GetFaceURL() string {
	if x != nil {
		return x.FaceURL
	}
	return ""
}

// CreateFriendRequest
type FriendListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID    string           `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`                                                                                                // 用户id
	ChangTime map[string]int64 `protobuf:"bytes,2,rep,name=changTime,proto3" json:"changTime,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` //好友信息更新时间列表
}

func (x *FriendListReq) Reset() {
	*x = FriendListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_model_v2_friend_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendListReq) ProtoMessage() {}

func (x *FriendListReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_model_v2_friend_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendListReq.ProtoReflect.Descriptor instead.
func (*FriendListReq) Descriptor() ([]byte, []int) {
	return file_common_model_v2_friend_proto_rawDescGZIP(), []int{1}
}

func (x *FriendListReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *FriendListReq) GetChangTime() map[string]int64 {
	if x != nil {
		return x.ChangTime
	}
	return nil
}

// FriendListReply
type FriendListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*FriendItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // 好友列表
}

func (x *FriendListReply) Reset() {
	*x = FriendListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_model_v2_friend_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendListReply) ProtoMessage() {}

func (x *FriendListReply) ProtoReflect() protoreflect.Message {
	mi := &file_common_model_v2_friend_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendListReply.ProtoReflect.Descriptor instead.
func (*FriendListReply) Descriptor() ([]byte, []int) {
	return file_common_model_v2_friend_proto_rawDescGZIP(), []int{2}
}

func (x *FriendListReply) GetItems() []*FriendItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_common_model_v2_friend_proto protoreflect.FileDescriptor

var file_common_model_v2_friend_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x76,
	0x32, 0x2f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13,
	0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x76, 0x32, 0x22, 0x52, 0x0a, 0x0a, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x66, 0x61, 0x63, 0x65, 0x55, 0x52, 0x4c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x66, 0x61, 0x63, 0x65, 0x55, 0x52, 0x4c, 0x22, 0xb6, 0x01, 0x0a, 0x0d, 0x46, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x4f, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76, 0x32, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x54, 0x69,
	0x6d, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x54, 0x69,
	0x6d, 0x65, 0x1a, 0x3c, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x48, 0x0a, 0x0f, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x35, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76, 0x32, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x42, 0x4c, 0x0a, 0x13, 0x61, 0x70,
	0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x76,
	0x32, 0x50, 0x01, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x62, 0x72, 0x69, 0x61, 0x6e, 0x2d, 0x67, 0x6f, 0x64, 0x2f, 0x78, 0x79, 0x2d, 0x61, 0x70, 0x69,
	0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2f, 0x76, 0x32, 0x3b, 0x76, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_model_v2_friend_proto_rawDescOnce sync.Once
	file_common_model_v2_friend_proto_rawDescData = file_common_model_v2_friend_proto_rawDesc
)

func file_common_model_v2_friend_proto_rawDescGZIP() []byte {
	file_common_model_v2_friend_proto_rawDescOnce.Do(func() {
		file_common_model_v2_friend_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_model_v2_friend_proto_rawDescData)
	})
	return file_common_model_v2_friend_proto_rawDescData
}

var file_common_model_v2_friend_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_model_v2_friend_proto_goTypes = []interface{}{
	(*FriendItem)(nil),      // 0: api.common.model.v2.FriendItem
	(*FriendListReq)(nil),   // 1: api.common.model.v2.FriendListReq
	(*FriendListReply)(nil), // 2: api.common.model.v2.FriendListReply
	nil,                     // 3: api.common.model.v2.FriendListReq.ChangTimeEntry
}
var file_common_model_v2_friend_proto_depIdxs = []int32{
	3, // 0: api.common.model.v2.FriendListReq.changTime:type_name -> api.common.model.v2.FriendListReq.ChangTimeEntry
	0, // 1: api.common.model.v2.FriendListReply.items:type_name -> api.common.model.v2.FriendItem
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_model_v2_friend_proto_init() }
func file_common_model_v2_friend_proto_init() {
	if File_common_model_v2_friend_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_model_v2_friend_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_model_v2_friend_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_model_v2_friend_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_model_v2_friend_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_model_v2_friend_proto_goTypes,
		DependencyIndexes: file_common_model_v2_friend_proto_depIdxs,
		MessageInfos:      file_common_model_v2_friend_proto_msgTypes,
	}.Build()
	File_common_model_v2_friend_proto = out.File
	file_common_model_v2_friend_proto_rawDesc = nil
	file_common_model_v2_friend_proto_goTypes = nil
	file_common_model_v2_friend_proto_depIdxs = nil
}
