// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v2

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 获取好友信息失败
func IsGetFriendListFail(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == FriendErrorReason_GET_FRIEND_LIST_FAIL.String() && e.Code == 410
}

// 获取好友信息失败
func ErrorGetFriendListFail(format string, args ...interface{}) *errors.Error {
	return errors.New(410, FriendErrorReason_GET_FRIEND_LIST_FAIL.String(), fmt.Sprintf(format, args...))
}
