// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package err

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 没有权限
func IsNoPermission(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == CommonErrorReason_NoPermission.String() && e.Code == 402
}

// 没有权限
func ErrorNoPermission(format string, args ...interface{}) *errors.Error {
	return errors.New(402, CommonErrorReason_NoPermission.String(), fmt.Sprintf(format, args...))
}

// 没有数据
func IsNoData(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == CommonErrorReason_NoData.String() && e.Code == 404
}

// 没有数据
func ErrorNoData(format string, args ...interface{}) *errors.Error {
	return errors.New(404, CommonErrorReason_NoData.String(), fmt.Sprintf(format, args...))
}
