// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: group/v2/group_error.proto

package v2

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupErrorReason int32

const (
	// 获取群信息失败
	GroupErrorReason_GET_GROUP_LIST_FAIL GroupErrorReason = 0
)

// Enum value maps for GroupErrorReason.
var (
	GroupErrorReason_name = map[int32]string{
		0: "GET_GROUP_LIST_FAIL",
	}
	GroupErrorReason_value = map[string]int32{
		"GET_GROUP_LIST_FAIL": 0,
	}
)

func (x GroupErrorReason) Enum() *GroupErrorReason {
	p := new(GroupErrorReason)
	*p = x
	return p
}

func (x GroupErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GroupErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_group_v2_group_error_proto_enumTypes[0].Descriptor()
}

func (GroupErrorReason) Type() protoreflect.EnumType {
	return &file_group_v2_group_error_proto_enumTypes[0]
}

func (x GroupErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GroupErrorReason.Descriptor instead.
func (GroupErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_group_v2_group_error_proto_rawDescGZIP(), []int{0}
}

var File_group_v2_group_error_proto protoreflect.FileDescriptor

var file_group_v2_group_error_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2f, 0x76, 0x32, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x70,
	0x69, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x76, 0x31, 0x1a, 0x13, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x73, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a,
	0x37, 0x0a, 0x10, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x13, 0x47, 0x45, 0x54, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50,
	0x5f, 0x4c, 0x49, 0x53, 0x54, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x10, 0x00, 0x1a, 0x04, 0xa8, 0x45,
	0x9a, 0x03, 0x1a, 0x04, 0xa0, 0x45, 0xf4, 0x03, 0x42, 0x3e, 0x0a, 0x0c, 0x61, 0x70, 0x69, 0x2e,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x76, 0x32, 0x50, 0x01, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x72, 0x69, 0x61, 0x6e, 0x2d, 0x67, 0x6f, 0x64,
	0x2f, 0x78, 0x79, 0x2d, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x2f, 0x76, 0x32, 0x3b, 0x76, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_group_v2_group_error_proto_rawDescOnce sync.Once
	file_group_v2_group_error_proto_rawDescData = file_group_v2_group_error_proto_rawDesc
)

func file_group_v2_group_error_proto_rawDescGZIP() []byte {
	file_group_v2_group_error_proto_rawDescOnce.Do(func() {
		file_group_v2_group_error_proto_rawDescData = protoimpl.X.CompressGZIP(file_group_v2_group_error_proto_rawDescData)
	})
	return file_group_v2_group_error_proto_rawDescData
}

var file_group_v2_group_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_group_v2_group_error_proto_goTypes = []interface{}{
	(GroupErrorReason)(0), // 0: api.Group.v1.GroupErrorReason
}
var file_group_v2_group_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_group_v2_group_error_proto_init() }
func file_group_v2_group_error_proto_init() {
	if File_group_v2_group_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_group_v2_group_error_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_group_v2_group_error_proto_goTypes,
		DependencyIndexes: file_group_v2_group_error_proto_depIdxs,
		EnumInfos:         file_group_v2_group_error_proto_enumTypes,
	}.Build()
	File_group_v2_group_error_proto = out.File
	file_group_v2_group_error_proto_rawDesc = nil
	file_group_v2_group_error_proto_goTypes = nil
	file_group_v2_group_error_proto_depIdxs = nil
}
